name: Java CI with Maven
'on':
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - run: mkdir deployment && cp target/*.war deployment
    - run: pwd && ls && ls target/* && ls deployment/*
    - run: curl --upload-file deployment/mvnwebapp.war "http://deployer:deployer@146.148.32.188:8081/manager/text/deploy?path=/githubaction&update=true"
