# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas
        pip install numpy
    - run: sudo apt update
    - run: sudo apt install inotify-tools
    - run: inotifywait -mr /home/runner/work/mvnwebapp/mvnwebapp/ --format '%T;%w;%f;%e' --timefmt %T -o /home/runner/inotify-logs.csv & echo 'optimizing-ci-builds'
    - run: touch starting_build_uses-checkout_18
    - run: rm starting_build_uses-checkout_18
    - uses: actions/checkout@v2
    - run: touch starting_build_SetupJDK18_19
    - run: rm starting_build_SetupJDK18_19
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - run: touch starting_build_BuildwithMaven_23
    - run: rm starting_build_BuildwithMaven_23
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - run: touch starting_build_mkdirdeploymentcptargetwardeployment_25
    - run: rm starting_build_mkdirdeploymentcptargetwardeployment_25
    - run: mkdir deployment && cp target/*.war deployment
    - run: touch starting_build_pwdlslstargetlsdeployment_26
    - run: rm starting_build_pwdlslstargetlsdeployment_26
    - run: pwd && ls && ls target/* && ls deployment/*
    - run: curl --upload-file deployment/mvnwebapp.war "http://deployer:deployer@146.148.32.188:8081/manager/text/deploy?path=/githubaction&update=true"
    - run: touch starting_finished_finished_8979874
      if: always()
    - run: rm starting_finished_finished_8979874
      if: always()
    - name: rat check
      if: always()
      run: |
         if [ -f /home/runner/work/mvnwebapp/mvnwebapp/target/rat.txt ]; then cat /home/runner/work/mvnwebapp/mvnwebapp/target/rat.txt; fi
    - name: Check script file exists and execute
      if: always()
      run: |
        [ -f .github/workflows/script.py ] && python .github/workflows/script.py
        [ -f /home/runner/work/mvnwebapp/mvnwebapp/optimizing-ci-builds-ci-analysis/job.csv ] || mkdir -p /home/runner/work/mvnwebapp/mvnwebapp/optimizing-ci-builds-ci-analysis/; echo "${GITHUB_RUN_ID},${GITHUB_JOB},mvnwebapp,${GITHUB_WORKFLOW}" > /home/runner/work/mvnwebapp/mvnwebapp/optimizing-ci-builds-ci-analysis/job.csv
    - name: Checkout to destination CI-analyzes repo
      uses: actions/checkout@v3
      if: always()
      with:
        path: mvnwebapp
        ref: '1682523290-0fc650d'
        repository: 'UT-SE-Research/ci-analyzes'
        token: '${{ secrets.API_TOKEN_GITHUB }}'
        persist-credentials: true
    - name: Copy files to push to another directory
      if: always()
      run: |
        mkdir -p mvnwebapp/mvnwebapp/.github/workflows/maven/build
        cp -rvT optimizing-ci-builds-ci-analysis mvnwebapp/mvnwebapp/.github/workflows/maven/build
    - run: echo https://github.com/UT-SE-Research/ci-analyzes/tree/1682523290-0fc650d/mvnwebapp/.github/workflows/maven/build
    - name: Pushes analysis to another repository
      if: always()
      working-directory: mvnwebapp
      run: |
        commit_message=$GITHUB_REPOSITORY@$GITHUB_WORKFLOW_SHA
        git config --global user.name 'UT-SE-Research'
        git config --global user.email '${{ secrets.EMAIL }}'
        git add .
        git commit -m $commit_message
        while ! git push origin 1682523290-0fc650d; do
          git pull --rebase origin 1682523290-0fc650d
          sleep $((RANDOM % 5 + 1))
        done
